countries = ["Spain", "China", "England", "Thailand", "India"]
print(countries)
print(sorted(countries))
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.reverse()
print(countries)

print("\nThere are " + str(len(countries)) + " countries in this list")
print("\nThe first country in this list is " + countries[0] + ".")
