countries = ["Spain", "China", "England", "Thailand", "India"]
print(countries)
print(sorted(countries))
print(countries)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
countries.reverse()
print(countries)
